### ISSUE TITLE
Escape Pango special characters

### ISSUE THREAD

**Issue by ckudera** [un-def/i3blocks-spotify-persist#3]
First, thank you for the great i3block.

At my system, song titles which contain a `&`, `<`, or `>` were not displayed. According to this [Github Issue](https://github.com/vivien/i3blocks/issues/226) this are special characters in Pango which must be escaped.

I modified the code:
```python
if not only_if_changed or self._prev_info != info:
    info = info.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    print(info, flush=True)
    self._prev_info = info
```

Maybe this helps somebody else :)

**Comment by un-def** [comment]
The blocklet already has an option to escape Pango markup: https://github.com/un-def/i3blocks-spotify-persist#markup_escape

You can either set this option to `true` in JSON config (see [config example](https://github.com/un-def/i3blocks-spotify-persist#config-example)) or use command-line flag `--markup-escape`:

```
$ i3blocks-spotify-persist                
Playing: Lorn – Glass & Silver
^C
$ i3blocks-spotify-persist --markup-escape
Playing: Lorn – Glass &amp; Silver
^C
```

**Comment by ckudera** [comment]
Thanks, I overlooked that setting.
