### ISSUE TITLE
Click not working with persist interval

### ISSUE THREAD

**Issue by kalenpw** [un-def/i3blocks-spotify-persist#4]
Not sure if I'm missing some part of config since I see this was implemented, but when I have the next, prev, play/pause buttons set with persistent interval they don't work. Setting them to interval works, but is obviously not ideal.

i3blocks version 1.4-4
Ubuntu 18.04

**Comment by un-def** [comment]
Click events for persistent blocklets are supported since i3blocks version 1.5 (check the last item of the [Features](https://github.com/un-def/i3blocks-spotify-persist#features) section of the README), you need to upgrade.

**Comment by kalenpw** [comment]
Not sure how I missed that I suppose that's what I get for doing this late at night. 

Thanks for the quick help!
