### ISSUE TITLE
Crashing when sending signal to i3blocks

### ISSUE THREAD

**Issue by rojnwa** [un-def/i3blocks-spotify-persist#5]
As soon as you send a signal to i3blocks, your script crashes with the error:

`[1]    182634 unknown signal  i3blocks-spotify-persist`

even tho i3blocks is not configured to send any signal to that script. Really annoying because I use signals to update my blockets (for example when adjusting volume).

![pic-selected-200801-1505-06](https://user-images.githubusercontent.com/19150352/89102342-930ab200-d408-11ea-9a8e-ac454ddc8b05.png)

**Comment by un-def** [comment]
It's not `i3blocks` but you kill the blocklet. The positional argument of the `pkill` is a regular expression, and the `i3blocks` pattern matches any process name containing the `i3blocks` string:

```
$ pgrep -a i3blocks
1934 i3blocks -c /home/user/.config/i3blocks/config
1956 /home/user/.local/pipx/venvs/i3blocks-spotify-persist/bin/python /home/user/.local/bin/i3blocks-spotify-persist
```

Use the `-x` flag:

> ```
> -x, --exact
>        Only match processes whose names (or command line if -f is specified) exactly match the pattern.
> ```

```
$ pgrep -ax i3blocks
1934 i3blocks -c /home/user/.config/i3blocks/config
```

That is, use `pkill -x -RTMIN+11 i3blocks`.

**Comment by rojnwa** [comment]
> It's not `i3blocks` but you kill the blocklet. The positional argument of the `pkill` is a regular expression, and the `i3blocks` pattern matches any process name containing the `i3blocks` string:
> 
> ```
> $ pgrep -a i3blocks
> 1934 i3blocks -c /home/user/.config/i3blocks/config
> 1956 /home/user/.local/pipx/venvs/i3blocks-spotify-persist/bin/python /home/user/.local/bin/i3blocks-spotify-persist
> ```
> 
> Use the `-x` flag:
> 
> > ```
> > -x, --exact
> >        Only match processes whose names (or command line if -f is specified) exactly match the pattern.
> > ```
> 
> ```
> $ pgrep -ax i3blocks
> 1934 i3blocks -c /home/user/.config/i3blocks/config
> ```
> 
> That is, use `pkill -x -RTMIN+11 i3blocks`.

Awesome thanks, didn't know that. Unluckily I've already switched over to another blocklet which I modified myself so it scrolls as soon as the string exceeds 25 characters.
