### ISSUE TITLE
Very high CPU usage

### ISSUE THREAD

**Issue by cvincent** [un-def/i3blocks-spotify-persist#6]
I noticed last night that the process was pegging my CPU and had to kill it.

**Comment by un-def** [comment]
This looks like an issue I'm already aware of, but I need a little clarification: was the Spotify app closed at that time?

**Comment by cvincent** [comment]
Unfortunately, I don't remember.

**Comment by un-def** [comment]
I've just released a new version [1.2.0](https://github.com/un-def/i3blocks-spotify-persist/releases/tag/1.2.0) where this issue should be fixed, at least I can no longer reproduce it. If the issue is still present in this version, please feel free to reopen the issue.
