### ISSUE TITLE
Python 3.10 errors when installing

### ISSUE THREAD

**Issue by mark00h** [un-def/i3blocks-spotify-persist#7]
Hello. Sorry, this is my first Github error report ever so I might miss some etiquette there and there. I tried to install the package today with pip according to the instructions, however it threw bunch of errors. They all seem to be related to Python 3.10, which isn't specified in "setup.cfg". I am on Arch Linux.

Other way to get this working is to put the "i3blocks_mpris.py" to directory you want. In i3blocks configuration file, I had to put "python3" first in the "command="-line or the program wouldn't run at all. Works perfectly well now, thanks.

`[mpris]`
`command=python3 /directory/to/i3blocks_mpris.py -c /directory/to/config.json`
`interval=persist`
`markup=pango`

**Comment by un-def** [comment]
Sorry for the late response. I'm not familiar with Arch Linux but using my general knowledge of Linux I managed to install the blocklet via `pip` on Python 3.10:

```
# install build dependencies
pacman -Sy gcc pkgconfig make cairo gobject-introspection

# install the blocklet
pip install i3blocks-mpris
```

Could you provide the full output of the `pip install` command?
